# Generated by Django 5.0.6 on 2024-08-17 09:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReceivedEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender", models.EmailField(max_length=254)),
                ("recipient", models.EmailField(max_length=254)),
                (
                    "cc",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated list of CC email addresses",
                    ),
                ),
                (
                    "bcc",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated list of BCC email addresses",
                    ),
                ),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField()),
                (
                    "received_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "in_reply_to",
                    models.CharField(max_length=255, null=True, unique=True),
                ),
                (
                    "message_id",
                    models.CharField(max_length=255, null=True, unique=True),
                ),
                ("thread_id", models.CharField(blank=True, max_length=255, null=True)),
                ("full_body", models.TextField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_emails",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="email_attachments/")),
                ("filename", models.CharField(max_length=255)),
                ("content_type", models.CharField(max_length=100)),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="receiving.receivedemail",
                    ),
                ),
            ],
        ),
    ]
