# Generated by Django 5.0.6 on 2024-07-25 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receiving", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receivedemail",
            name="message_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
