# Generated by Django 5.0.6 on 2024-07-25 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receiving", "0002_alter_receivedemail_message_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="receivedemail",
            name="bcc",
            field=models.TextField(
                blank=True, help_text="Comma-separated list of BCC email addresses"
            ),
        ),
        migrations.AddField(
            model_name="receivedemail",
            name="cc",
            field=models.TextField(
                blank=True, help_text="Comma-separated list of CC email addresses"
            ),
        ),
    ]
