# Generated by Django 5.0.6 on 2024-07-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="email",
            options={"ordering": ["-received_at"]},
        ),
        migrations.RemoveField(
            model_name="email",
            name="body",
        ),
        migrations.AddField(
            model_name="email",
            name="body_html",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="email",
            name="body_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="email",
            name="message_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="email",
            name="received_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
