# Generated by Django 5.0.6 on 2024-08-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="budget",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="contact",
            name="company_size",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="decision_maker_role",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="contact",
            name="icp_score",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="contact",
            name="industry",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="contact",
            name="location",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="contact",
            name="pain_points",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="previous_engagement",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="contact",
            name="technology_stack",
            field=models.TextField(blank=True),
        ),
    ]
