# Generated by Django 5.0.6 on 2024-08-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0002_contact_budget_contact_company_size_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="budget",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=5000, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="company_size",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="decision_maker_role",
            field=models.CharField(blank=True, default="VP", max_length=100),
        ),
        migrations.AlterField(
            model_name="contact",
            name="industry",
            field=models.CharField(blank=True, default="Technology", max_length=100),
        ),
        migrations.AlterField(
            model_name="contact",
            name="location",
            field=models.CharField(blank=True, default="London", max_length=100),
        ),
        migrations.AlterField(
            model_name="contact",
            name="pain_points",
            field=models.TextField(blank=True, default="efficiency"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="previous_engagement",
            field=models.TextField(blank=True, default="demo"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="technology_stack",
            field=models.TextField(blank=True, default="Python"),
        ),
    ]
