databases:
  - name: emailTrackerDB
    plan: free
    databaseName: email_tracker_db
    user: email_tracker_user

services:
  - type: web
    plan: free
    name: emailTracker
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn email_tracker.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: emailTrackerDB
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
