# Generated by Django 5.0.6 on 2024-07-31 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("conversations", "0001_initial"),
        ("receiving", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversationmessage",
            name="received_email",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="receiving.receivedemail",
            ),
        ),
    ]
