# Generated by Django 5.0.6 on 2024-08-20 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="unread",
            field=models.BooleanField(default=True),
        ),
    ]
