# Generated by Django 5.0.6 on 2024-07-26 08:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0001_initial"),
        ("receiving", "0003_receivedemail_bcc_receivedemail_cc"),
        ("sending", "0005_rename_email_sentemail"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="conversationmessage",
            name="received_email",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="receiving.receivedemail",
            ),
        ),
        migrations.AlterField(
            model_name="conversationmessage",
            name="sent_email",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="sending.sentemail",
            ),
        ),
        migrations.AlterField(
            model_name="conversationmessage",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name="conversationparticipant",
            unique_together={("conversation", "email")},
        ),
    ]
