# Generated by Django 5.0.6 on 2024-08-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0002_conversation_unread"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="unread_count",
            field=models.IntegerField(default=0),
        ),
    ]
