# Generated by Django 5.0.6 on 2024-08-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0003_conversation_unread_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="is_new",
            field=models.BooleanField(default=True),
        ),
    ]
