# Generated by Django 5.0.6 on 2024-08-01 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sending", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sentemail",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_emails",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="link",
            name="email",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sending.sentemail"
            ),
        ),
        migrations.AddField(
            model_name="trackingpixeltoken",
            name="email",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sending.sentemail"
            ),
        ),
    ]
