# Generated by Django 5.0.6 on 2024-08-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sending", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sentemail",
            name="bounce_reason",
            field=models.CharField(
                blank=True, default="ImplementationPending", max_length=255, null=True
            ),
        ),
        migrations.AddField(
            model_name="sentemail",
            name="campaign_id",
            field=models.CharField(
                blank=True, default="default_campaign", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="sentemail",
            name="is_bounced",
            field=models.BooleanField(default=False),
        ),
    ]
