# Generated by Django 5.0.6 on 2024-07-25 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("receiving", "0002_alter_receivedemail_message_id"),
        ("sending", "0002_email_message_id_email_thread_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="in_reply_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_replies",
                to="receiving.receivedemail",
            ),
        ),
    ]
