# Generated by Django 5.0.6 on 2024-07-26 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0001_initial"),
        ("receiving", "0003_receivedemail_bcc_receivedemail_cc"),
        ("sending", "0004_email_bcc_email_cc"),
        ("tracking", "0017_delete_unsubscribeduser"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Email",
            new_name="SentEmail",
        ),
    ]
