# Generated by Django 5.0.6 on 2024-08-28 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emailinteraction",
            name="related_open",
        ),
        migrations.AlterField(
            model_name="emailinteraction",
            name="interaction_type",
            field=models.CharField(
                choices=[("OPEN", "Open"), ("CLICK", "Click")], max_length=20
            ),
        ),
    ]
