# Generated by Django 5.0.6 on 2024-06-19 10:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0002_email_ip_address_email_opened_at_email_user_agent_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="email",
            name="ip_address",
        ),
        migrations.RemoveField(
            model_name="email",
            name="opened_at",
        ),
        migrations.RemoveField(
            model_name="email",
            name="user_agent",
        ),
        migrations.AlterField(
            model_name="email",
            name="sent_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="trackinglog",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="trackinglog",
            name="opened_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="trackinglog",
            name="user_agent",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tracking.email"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LinkClick",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("clicked_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tracking.link"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="TrackedLink",
        ),
    ]
