# Generated by Django 5.0.6 on 2024-08-31 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0002_remove_emailinteraction_related_open_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailinteraction",
            name="tracking_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tracking.trackingitem",
            ),
        ),
    ]
