# Generated by Django 5.0.6 on 2024-06-20 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0003_remove_email_ip_address_remove_email_opened_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnsubscribedUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
