# Generated by Django 4.1.13 on 2024-06-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0005_emailbatch"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailbatch",
            name="_email_data",
            field=models.TextField(default="[]"),
        ),
    ]
