# Generated by Django 4.1.13 on 2024-06-26 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0007_remove_emailbatch__email_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailbatch",
            name="send_time",
            field=models.TimeField(),
        ),
    ]
