# Generated by Django 4.1.13 on 2024-07-01 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0009_alter_emailbatch_batch_size_alter_emailbatch_body_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="EmailBatch",
        ),
    ]
