# Generated by Django 5.0.6 on 2024-07-17 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0012_trackinglog_is_expired_open_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="linkclick",
            name="connection",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="linkclick",
            name="device_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="linkclick",
            name="geo_location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="linkclick",
            name="host",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="linkclick",
            name="language",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="linkclick",
            name="method",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="linkclick",
            name="protocol",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="linkclick",
            name="referer",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="linkclick",
            name="screen_resolution",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="trackinglog",
            name="connection",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="trackinglog",
            name="device_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="trackinglog",
            name="geo_location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="trackinglog",
            name="host",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="trackinglog",
            name="language",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="trackinglog",
            name="method",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="trackinglog",
            name="protocol",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="trackinglog",
            name="referer",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="trackinglog",
            name="screen_resolution",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
