# Generated by Django 5.0.6 on 2024-07-17 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0013_linkclick_connection_linkclick_device_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="email",
            name="sender",
            field=models.EmailField(default="noreply@example.com", max_length=254),
        ),
    ]
