# Generated by Django 5.0.6 on 2024-07-18 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sending", "0001_initial"),
        ("tracking", "0015_alter_linkclick_connection_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trackinglog",
            name="email",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sending.email"
            ),
        ),
        migrations.RemoveField(
            model_name="link",
            name="email",
        ),
        migrations.RemoveField(
            model_name="trackingpixeltoken",
            name="email",
        ),
        migrations.AlterField(
            model_name="linkclick",
            name="link",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="sending.link"
            ),
        ),
        migrations.DeleteModel(
            name="Email",
        ),
        migrations.DeleteModel(
            name="TrackingPixelToken",
        ),
        migrations.DeleteModel(
            name="Link",
        ),
    ]
