# Generated by Django 5.0.6 on 2024-07-26 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sending", "0005_rename_email_sentemail"),
        ("tracking", "0017_delete_unsubscribeduser"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("interaction_type", models.CharField(max_length=50)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sending.sentemail",
                    ),
                ),
                (
                    "related_open",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tracking.emailinteraction",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GenuineOpen",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sending.sentemail",
                    ),
                ),
            ],
        ),
    ]
