# Generated by Django 5.0.6 on 2024-07-27 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sending", "0005_rename_email_sentemail"),
        ("tracking", "0018_emailinteraction_genuineopen"),
    ]

    operations = [
        migrations.AddField(
            model_name="genuineopen",
            name="open_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tracking.emailinteraction",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="genuineopen",
            unique_together={("email", "open_event")},
        ),
    ]
